#!/bin/bash
set -e

sed -i -r 's/(listen .*443)/\1;#/g; s/(ssl_(certificate|certificate_key|trusted_certificate) )/#;#\1/g' /etc/nginx/sites-available/maidenlane.xyz.conf
sudo nginx -t && sudo systemctl reload nginx
certbot certonly --webroot -d maidenlane.xyz -d www.maidenlane.xyz -d cdn.maidenlane.xyz --email admin@manifoldfinance.com -w /var/www/_letsencrypt -n --agree-tos --force-renewal
sleep 1
sed -i -r 's/#?;#//g' /etc/nginx/sites-available/maidenlane.xyz.conf
sudo nginx -t && sudo systemctl reload nginx
sleep 1
echo -e '#!/bin/bash\nnginx -t && systemctl reload nginx' | sudo tee /etc/letsencrypt/renewal-hooks/post/nginx-reload.sh
sudo chmod a+x /etc/letsencrypt/renewal-hooks/post/nginx-reload.sh
